### ISSUE TITLE
[feature] allow toc-extract-page-ocr perform ad-hoc OCR on selected pages... 

### ISSUE THREAD

**Issue by oatmealm** [dalanicolai/toc-mode#2]
I've been using `toc-mode` to run `tesseract` ad-hoc simply to get text of pages as needed... so not move beyond the cleanup stage. 

Would be great to have that as a feature... I need to test further, but I had an impression the if I kill the clean up buffer, something still hangs around and subsequent attempts to do an ad-hoc, I some time get an empty buffer and I don't see the message echoed about pages being scanned...

**Comment by dalanicolai** [comment]
Ah, do you know some elisp already? Because then you could have quite easily hacked/copied this from the ocr extract function.
Anyway, I have added a function `toc-extract-only` (which is largely a copy from the original extract function).

**Comment by oatmealm** [comment]
Works!

I'd look at the code when I have time and see how I can contribute. My experience with elisp is not beyond config stuff though....


Regardless, would it be better to rename utilities like this to something like 'extract-page-content-only', or something similar, so to distinguish them from functions that do toc specific work?

**Comment by dalanicolai** [comment]
Great! Well I don't expect you to contribute, I was just saying it because hacking on elisp is quite straightforward and a lot of fun. Making tools like this package is not too complicated.
Thanks for thinking with me about the naming, but I think it is nice to keep the toc in the name to indicate that the function belongs to some external package (i.e. toc-mode, it might be a convention too).
