### ISSUE TITLE
things I learned on a first go, maybe for docs or to help others

### ISSUE THREAD

**Issue by mooseyboots** [dalanicolai/toc-mode#6]
thanks for this great library. i have wanted this functionality for a while and had no luck outside of emacs. 

i just used it for the first time and thought i would share my experience in case it helps someone else, or in case you want to edit your readme, or in case i have a few more things to learn!

* initially i ran into a problem where some elements of my contents' text lines were being processed as pages numbers in toc-tabulated mode. my main wish at this point was the ability to return to the previous stage to try to work out what was wrong. not sure if that is possible, but it cd be helpful for fixing such errors, which are disorienting and otherwise require the user to start over without having worked out how to solve it.
* i realized that this happens to any lines that don't end in a page number. i'm not sure if there is an easy way to handle such items, but contents pages often have elements like this. in my case the first item this happened to was 'inhalt', ie 'contents'. :) if there is no easy way to handle them (would a dummy taken from the next line's number work? because then you can fix it in toc-tabulated anyway), it might good to mention in your docs that all lines must end in a page number. (maybe its known that pdf outlines shdnt have any such items, i'm not sure.)
* for me, any empty lines in my toc (which my ocr scan produced) led to broken entries in the toc: they are converted in to the pdf's last page number enclosed in brackets as top level items. / if there is no way to handle (just cut?) empty lines, maybe also mention in the cleanup section of your docs to not include any?
* is there a way to edit existing toc's? i see i can extract an existing outline with ```toc-extract-outline```, but it doesn't seem to work with your dispatch/process. i can only save it as a text file, not embed it back into the pdf. this would be a big help in dealing with imperfectly created toc's or for modifying any existing ones we come across.

thx again for yr package. it will definitely come in very handy.

**Comment by dalanicolai** [comment]
Hi sorry for the late reply, but I think that I never got notified about this issue. Probably I have to explicitly watch this repo to get notified about it; I will investigate it.

Anyway, thank you for your feedback. Maybe the README is not very clear, but probably that is because there is a lot of information in it. I think I covered most points you are describing already in the README.

For your first point, Section 1 mentions that you can get the raw text (without cleanup) by prefixing the extraction command with a universal-argument. Then Section 2 describes how to cleanup the extracted text and what format is expected (also it provides an example for how to use replace-regexp to cleanup the text).

So your second point is covered by the first line of Section 2. I am not sure if you have seen it or if it was not clear. Anyway, I am happy with any suggestion for how to improve that part.

For point 3, I have mentioned in the intro, that in each stage you can use `C-h m` and `M-x <mode-name>` to get more information about shortcuts and available functions. So if you try `M-x toc-cleanup` you will find that there is a function `toc-cleanup-blank-lines` available.
But indeed it might be handy to remind in the Section about `C-h m` and `M-x ...`, and to emphasize that there should be no blank lines.

To edit an existing TOC, you can extract the outline then clean it up and subsequently use that text in a `toc-cleanup` buffer that you got via `toc-extract-pages(-ocr)`. Just replace all the text with the cleaned up TOC, and proceed as usual. For sure, this workflow can get improved. Just when I wrote the package, at some point I did not want to spend more time on it. But maybe now I can have a fresh look at it again.

I will update the README tomorrow (it is really late now here), and probably soon look into the extract outline workflow.

Again, thanks for the feedback!
