### ISSUE TITLE
toc-extract-only empty output

### ISSUE THREAD

**Issue by oatmealm** [dalanicolai/toc-mode#7]
Hi there! Hope you're well. I've been making the most of your library for a long time. Thanks again, it's really appreciated.

I've noticed recently that running `toc-extract-only` returns no/empty results. The out TXT buffer is created, but there's no content. There are also no errors or warning, with debug enabled.

**Comment by dalanicolai** [comment]
Hi! Thanks for your feedback. As far as I know, the latest version of the package (which has not been updated for quite a while) is working fine (at least it is here). Have you tried already also on another pdf? Maybe you got a pdf without a text layer? Otherwise, maybe it is possible for you to share the document so that I can try to reproduce it?

Also, then I can come up with some idea for how to provide any feedback/warnings...

**Comment by oatmealm** [comment]
Hi. Thanks for the reply. 

I've only used the simple ocr function and it's seems to be a problem with all the PDFs I've tried ... it of course worked before regardless of having a text layer or not for outputting raw text of the ocr process with the selected languages.

**Comment by dalanicolai** [comment]
Sorry for the late reply, I had some distractions. Anyway, does extracting using the command `toc-extract-pages-ocr` work?
Otherwise, I guess you should test on your command line if the `tesseract` command works fine there...

**Comment by oatmealm** [comment]
> Sorry for the late reply, I had some distractions. Anyway, does extracting using the command `toc-extract-pages-ocr` work?
> 
> Otherwise, I guess you should test on your command line if the `tesseract` command works fine there...

Sorry. Missed your response. I'm on Guix now, and it's a bit complicated 🙄 I'll check again , but wouldn't I see an error if calling tesseract failed because it couldn't find language modules etc.?

**Comment by dalanicolai** [comment]
> I'm on Guix now

That sounds cool!

You mean that you do not see an error because, you see some error about language modules? In that case, I guess the error is about missing tesseract language modules (although I would expect tesseract to come with the English language module included). I am on Fedora, and here I can install language modules using `dnf install tesseract-langpack-...`. There exist also script modules for when trying for recognizing various scripts. I am not sure how it works on guix, but from [here](https://issues.guix.gnu.org/57151) I get the idea that tesseract should be usable. Otherwise, you can read about how to install 'traineddata' in [the tesseract documentation](https://tesseract-ocr.github.io/tessdoc/Installation.html).

**Comment by oatmealm** [comment]
I just checked again, and it seems that (executable-find "tesseract") indeed finds the executable, but when I try to ocr from the command line, from the command line, this is what I see...

````
tesseract --list-langs
List of available languages in "/home/uri/.config/tessdata/" (3):
ara
eng
heb

tesseract ~/Downloads/img.png -l heb
read_params_file: Can't open heb
Estimating resolution as 148
````

The strange thing is that I have this setup working perfectly fine in `gimagereader` .... so not sure what's happening.

**Comment by dalanicolai** [comment]
If you type `tesseract --help`, you see usage examples... you should enter some output file name (outputbase).

Also, it is hard to guess why there is no content in the .txt buffer. I would advise you to read about [edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html) and use it on `doc-toc-extract-only`. It is a very simple function that should be easy to edebug,

**Comment by oatmealm** [comment]
Thanks, i've missed that... it seems to work fine from the command line and now within emacs as well... !?!?! not sure what was the problem then... but glad it started... it's one of the things I use the most for my studies :)! 
Note prefect extraction in this case (i.e. when a paragraph starts in english or other language and then changes to Hebrew) but very usefull nontheless.

Thanks again.

![Screenshot from 2022-10-07 17-13-23](https://user-images.githubusercontent.com/68159077/194587915-337e9aaa-7e35-403a-9ed0-1d3d645428ff.png)
